import type { LucideIcon } from 'lucide-react'
import { Sparkles, LayoutDashboard, ImageIcon } from 'lucide-react'
import type { DesignConfig } from '@/lib/types'

export interface Template {
  id: string; name: string; desc: string
  category: 'minimal' | 'gradient' | 'image'
  colors: string[]; patch: Partial<DesignConfig>
}

export interface CategoryInfo {
  id: Template['category']; label: string; icon: LucideIcon
}

export const CATEGORIES: CategoryInfo[] = [
  { id: 'minimal', label: 'Minimal', icon: Sparkles },
  { id: 'gradient', label: 'Gradient', icon: LayoutDashboard },
  { id: 'image', label: 'Image', icon: ImageIcon },
]

export const TEMPLATES: Template[] = [
  { id: 'minimal-slate', name: 'Slate', desc: 'Clean flat design with subtle gray tones',
    category: 'minimal', colors: ['#64748B','#94A3B8','#FFFFFF','#F8FAFC'],
    patch: { primary_color: '#64748B', background_color: '#FFFFFF', header_type: 'none', header_height: 'small', card_style: 'flat', corner_radius: 'none', border_radius: 'small', question_layout: 'minimal', button_shape: 'square', button_size: 'small', heading_font: 'Inter', body_font: 'Inter', base_size: '15px', progress_bar: false, progress_style: 'line', progress_color: '#64748B', animations: false, page_transition: 'none', element_animation: 'none', form_width: 'narrow', page_padding: 'small', question_spacing: 'compact', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'checkmark', welcome_logo_color: '#64748B', welcome_text_color: '#334155', welcome_button_label: 'Start', welcome_button_color: '#64748B', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#e2e8f0', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'checkmark', thankyou_logo_color: '#64748B', thankyou_title_color: '#334155', thankyou_button_label: 'Back to home', thankyou_button_color: '#64748B', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#e2e8f0', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'minimal-navy', name: 'Navy', desc: 'Dark bold header with clean white canvas',
    category: 'minimal', colors: ['#1E293B','#334155','#F8FAFC','#E2E8F0'],
    patch: { primary_color: '#1E293B', background_color: '#F8FAFC', header_type: 'gradient', header_height: 'large', header_title_color: '#FFFFFF', header_desc_color: '#CBD5E1', card_style: 'soft_shadow', corner_radius: 'small', border_radius: 'small', question_layout: 'cards', button_shape: 'square', button_size: 'large', heading_font: 'Poppins', body_font: 'Inter', base_size: '17px', progress_bar: true, progress_style: 'line', progress_color: '#1E293B', animations: true, page_transition: 'slide', element_animation: 'fade', form_width: 'wide', page_padding: 'medium', question_spacing: 'standard', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'shield', welcome_logo_color: '#1E293B', welcome_text_color: '#1E293B', welcome_button_label: 'Start', welcome_button_color: '#1E293B', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#cbd5e1', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'shield', thankyou_logo_color: '#1E293B', thankyou_title_color: '#1E293B', thankyou_button_label: 'Back to home', thankyou_button_color: '#1E293B', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#cbd5e1', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'minimal-ivory', name: 'Ivory', desc: 'Warm off-white with amber accents and soft borders',
    category: 'minimal', colors: ['#D97706','#F59E0B','#FFFBEB','#FEF3C7'],
    patch: { primary_color: '#D97706', background_color: '#FFFBEB', header_type: 'solid', header_height: 'small', header_title_color: '#FFFFFF', header_desc_color: '#FDE68A', card_style: 'border', corner_radius: 'small', border_radius: 'small', question_layout: 'shared', button_shape: 'rounded', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '15px', progress_bar: false, progress_style: 'line', progress_color: '#D97706', animations: false, page_transition: 'none', element_animation: 'none', form_width: 'narrow', page_padding: 'small', question_spacing: 'compact', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'star', welcome_logo_color: '#D97706', welcome_text_color: '#78350F', welcome_button_label: 'Start', welcome_button_color: '#D97706', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#fffdf5', welcome_container_border_color: '#fde68a', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'star', thankyou_logo_color: '#D97706', thankyou_title_color: '#78350F', thankyou_button_label: 'Back to home', thankyou_button_color: '#D97706', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#fffdf5', thankyou_container_border_color: '#fde68a', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'minimal-snow', name: 'Snow', desc: 'Crisp white with icy blue accent and minimal layout',
    category: 'minimal', colors: ['#0EA5E9','#38BDF8','#F0F9FF','#FFFFFF'],
    patch: { primary_color: '#0EA5E9', background_color: '#F0F9FF', header_type: 'none', header_height: 'small', card_style: 'flat', corner_radius: 'medium', border_radius: 'small', question_layout: 'minimal', button_shape: 'rounded', button_size: 'small', heading_font: 'Inter', body_font: 'Inter', base_size: '15px', progress_bar: false, progress_style: 'line', progress_color: '#0EA5E9', animations: false, page_transition: 'none', element_animation: 'none', form_width: 'medium', page_padding: 'small', question_spacing: 'compact', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'droplets', welcome_logo_color: '#0EA5E9', welcome_text_color: '#0C4A6E', welcome_button_label: 'Start', welcome_button_color: '#0EA5E9', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#bae6fd', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'droplets', thankyou_logo_color: '#0EA5E9', thankyou_title_color: '#0C4A6E', thankyou_button_label: 'Back to home', thankyou_button_color: '#0EA5E9', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#bae6fd', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'minimal-rose', name: 'Rose', desc: 'Soft pink hues with elegant card borders',
    category: 'minimal', colors: ['#E11D48','#FB7185','#FFF1F2','#FFE4E6'],
    patch: { primary_color: '#E11D48', background_color: '#FFF1F2', header_type: 'solid', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#FECDD3', card_style: 'border', corner_radius: 'large', border_radius: 'medium', question_layout: 'cards', button_shape: 'pill', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '15px', progress_bar: true, progress_style: 'bar', progress_color: '#E11D48', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'medium', question_spacing: 'standard', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'heart', welcome_logo_color: '#E11D48', welcome_text_color: '#881337', welcome_button_label: 'Start', welcome_button_color: '#E11D48', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#fecdd3', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'heart', thankyou_logo_color: '#E11D48', thankyou_title_color: '#881337', thankyou_button_label: 'Back to home', thankyou_button_color: '#E11D48', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#fecdd3', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'gradient-purple', name: 'Purple Haze', desc: 'Vibrant purple gradient with polished cards',
    category: 'gradient', colors: ['#7C3AED','#A855F7','#F6F7FB','#FFFFFF'],
    patch: { primary_color: '#7C3AED', background_color: '#F6F7FB', header_type: 'gradient', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#E9D5FF', card_style: 'soft_shadow', corner_radius: 'large', border_radius: 'medium', question_layout: 'cards', button_shape: 'rounded', button_size: 'medium', heading_font: 'Poppins', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#7C3AED', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'gradient', gradient_color_1: '#7C3AED', gradient_color_2: '#A855F7', gradient_angle: '135deg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'sparkles', welcome_logo_color: '#7C3AED', welcome_text_color: '#4C1D95', welcome_button_label: 'Start', welcome_button_color: '#7C3AED', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#e9d5ff', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'sparkles', thankyou_logo_color: '#7C3AED', thankyou_title_color: '#4C1D95', thankyou_button_label: 'Back to home', thankyou_button_color: '#7C3AED', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#e9d5ff', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'gradient-ocean', name: 'Deep Ocean', desc: 'Calming blue gradient with soft card shadows',
    category: 'gradient', colors: ['#3B82F6','#60A5FA','#EFF6FF','#FFFFFF'],
    patch: { primary_color: '#3B82F6', background_color: '#EFF6FF', header_type: 'gradient', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#BFDBFE', card_style: 'soft_shadow', corner_radius: 'large', border_radius: 'medium', question_layout: 'cards', button_shape: 'rounded', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#3B82F6', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'gradient', gradient_color_1: '#3B82F6', gradient_color_2: '#1D4ED8', gradient_angle: '135deg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'waves', welcome_logo_color: '#3B82F6', welcome_text_color: '#1E3A5F', welcome_button_label: 'Start', welcome_button_color: '#3B82F6', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#bfdbfe', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'waves', thankyou_logo_color: '#3B82F6', thankyou_title_color: '#1E3A5F', thankyou_button_label: 'Back to home', thankyou_button_color: '#3B82F6', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#bfdbfe', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'gradient-sunset', name: 'Sunset Bliss', desc: 'Warm orange gradient with pill buttons',
    category: 'gradient', colors: ['#F97316','#FB923C','#FFF7ED','#FFFFFF'],
    patch: { primary_color: '#F97316', background_color: '#FFF7ED', header_type: 'gradient', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#FED7AA', card_style: 'soft_shadow', corner_radius: 'full', border_radius: 'medium', question_layout: 'cards', button_shape: 'pill', button_size: 'large', heading_font: 'Poppins', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#F97316', animations: true, page_transition: 'slide', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'gradient', gradient_color_1: '#F97316', gradient_color_2: '#EA580C', gradient_angle: '135deg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'sun', welcome_logo_color: '#F97316', welcome_text_color: '#7C2D12', welcome_button_label: 'Start', welcome_button_color: '#F97316', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#fffcf5', welcome_container_border_color: '#fed7aa', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'sun', thankyou_logo_color: '#F97316', thankyou_title_color: '#7C2D12', thankyou_button_label: 'Back to home', thankyou_button_color: '#F97316', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#fffcf5', thankyou_container_border_color: '#fed7aa', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'gradient-forest', name: 'Forest Glade', desc: 'Fresh emerald gradient with organic feel',
    category: 'gradient', colors: ['#22C55E','#4ADE80','#F0FDF4','#FFFFFF'],
    patch: { primary_color: '#22C55E', background_color: '#F0FDF4', header_type: 'gradient', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#BBF7D0', card_style: 'border', corner_radius: 'medium', border_radius: 'large', question_layout: 'shared', button_shape: 'rounded', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'bar', progress_color: '#22C55E', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'standard', background_type: 'gradient', gradient_color_1: '#22C55E', gradient_color_2: '#059669', gradient_angle: '135deg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'leaf', welcome_logo_color: '#22C55E', welcome_text_color: '#14532D', welcome_button_label: 'Start', welcome_button_color: '#22C55E', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#bbf7d0', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'leaf', thankyou_logo_color: '#22C55E', thankyou_title_color: '#14532D', thankyou_button_label: 'Back to home', thankyou_button_color: '#22C55E', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#bbf7d0', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'gradient-crimson', name: 'Crimson Tide', desc: 'Bold red gradient with square corners',
    category: 'gradient', colors: ['#EF4444','#F87171','#FEF2F2','#FFFFFF'],
    patch: { primary_color: '#EF4444', background_color: '#FEF2F2', header_type: 'gradient', header_height: 'large', header_title_color: '#FFFFFF', header_desc_color: '#FECACA', card_style: 'flat', corner_radius: 'none', border_radius: 'small', question_layout: 'cards', button_shape: 'square', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'bar', progress_color: '#EF4444', animations: true, page_transition: 'fade', element_animation: 'fade', form_width: 'medium', page_padding: 'medium', question_spacing: 'compact', background_type: 'gradient', gradient_color_1: '#EF4444', gradient_color_2: '#DC2626', gradient_angle: '135deg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'flame', welcome_logo_color: '#EF4444', welcome_text_color: '#7F1D1D', welcome_button_label: 'Start', welcome_button_color: '#EF4444', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#fecaca', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'flame', thankyou_logo_color: '#EF4444', thankyou_title_color: '#7F1D1D', thankyou_button_label: 'Back to home', thankyou_button_color: '#EF4444', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#fecaca', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'image-mountain', name: 'Mountain Ridge', desc: 'Dramatic mountain backdrop with clean overlay cards',
    category: 'image', colors: ['#1E293B','#475569','#F1F5F9','#FFFFFF'],
    patch: { primary_color: '#1E293B', background_color: '#F1F5F9', header_type: 'solid', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#CBD5E1', card_style: 'soft_shadow', corner_radius: 'small', border_radius: 'medium', question_layout: 'cards', button_shape: 'rounded', button_size: 'medium', heading_font: 'Poppins', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#1E293B', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'image', background_image_url: '/images/backgrounds/desktop/desktop-01.jpg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'mountain', welcome_logo_color: '#1E293B', welcome_text_color: '#1E293B', welcome_button_label: 'Start', welcome_button_color: '#1E293B', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#cbd5e1', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'mountain', thankyou_logo_color: '#1E293B', thankyou_title_color: '#1E293B', thankyou_button_label: 'Back to home', thankyou_button_color: '#1E293B', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#cbd5e1', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'image-forest', name: 'Forest Canopy', desc: 'Lush foliage background with green accents',
    category: 'image', colors: ['#22C55E','#4ADE80','#F0FDF4','#FFFFFF'],
    patch: { primary_color: '#22C55E', background_color: '#F0FDF4', header_type: 'image', header_height: 'large', header_image_url: '/images/backgrounds/minimal/minimal-01.jpg', header_title_color: '#FFFFFF', header_desc_color: '#BBF7D0', card_style: 'border', corner_radius: 'medium', border_radius: 'large', question_layout: 'shared', button_shape: 'rounded', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'bar', progress_color: '#22C55E', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'standard', background_type: 'solid',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'leaf', welcome_logo_color: '#22C55E', welcome_text_color: '#14532D', welcome_button_label: 'Start', welcome_button_color: '#22C55E', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#bbf7d0', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'leaf', thankyou_logo_color: '#22C55E', thankyou_title_color: '#14532D', thankyou_button_label: 'Back to home', thankyou_button_color: '#22C55E', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#bbf7d0', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'image-crimson', name: 'Crimson Peak', desc: 'Geometric pattern backdrop with bold red tones',
    category: 'image', colors: ['#EF4444','#F87171','#FEF2F2','#FFFFFF'],
    patch: { primary_color: '#EF4444', background_color: '#FEF2F2', header_type: 'solid', header_height: 'medium', header_title_color: '#FFFFFF', header_desc_color: '#FECACA', card_style: 'flat', corner_radius: 'none', border_radius: 'small', question_layout: 'cards', button_shape: 'square', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'bar', progress_color: '#EF4444', animations: true, page_transition: 'fade', element_animation: 'fade', form_width: 'medium', page_padding: 'medium', question_spacing: 'compact', background_type: 'image', background_image_url: '/images/backgrounds/pattern/pattern-01.jpg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'flag', welcome_logo_color: '#EF4444', welcome_text_color: '#7F1D1D', welcome_button_label: 'Start', welcome_button_color: '#EF4444', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#fecaca', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'flag', thankyou_logo_color: '#EF4444', thankyou_title_color: '#7F1D1D', thankyou_button_label: 'Back to home', thankyou_button_color: '#EF4444', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#fecaca', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'image-ocean', name: 'Ocean View', desc: 'Serene beach backdrop with blue card overlays',
    category: 'image', colors: ['#0EA5E9','#38BDF8','#F0F9FF','#FFFFFF'],
    patch: { primary_color: '#0EA5E9', background_color: '#F0F9FF', header_type: 'image', header_height: 'medium', header_image_url: '/images/backgrounds/gradient/gradient-01.jpg', header_title_color: '#FFFFFF', header_desc_color: '#BAE6FD', card_style: 'soft_shadow', corner_radius: 'large', border_radius: 'medium', question_layout: 'cards', button_shape: 'rounded', button_size: 'medium', heading_font: 'Inter', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#0EA5E9', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'image', background_image_url: '/images/backgrounds/desktop/desktop-02.jpg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'compass', welcome_logo_color: '#0EA5E9', welcome_text_color: '#0C4A6E', welcome_button_label: 'Start', welcome_button_color: '#0EA5E9', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#ffffff', welcome_container_border_color: '#bae6fd', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'compass', thankyou_logo_color: '#0EA5E9', thankyou_title_color: '#0C4A6E', thankyou_button_label: 'Back to home', thankyou_button_color: '#0EA5E9', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#ffffff', thankyou_container_border_color: '#bae6fd', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
  { id: 'image-night', name: 'Night Sky', desc: 'Dark starry backdrop with luminous purple accents',
    category: 'image', colors: ['#7C3AED','#A855F7','#1E0A3C','#2E1065'],
    patch: { primary_color: '#7C3AED', background_color: '#1E0A3C', header_type: 'none', header_height: 'small', card_style: 'soft_shadow', corner_radius: 'large', border_radius: 'medium', question_layout: 'cards', button_shape: 'rounded', button_size: 'medium', heading_font: 'Poppins', body_font: 'Inter', base_size: '16px', progress_bar: true, progress_style: 'line', progress_color: '#7C3AED', animations: true, page_transition: 'fade', element_animation: 'slide_up', form_width: 'medium', page_padding: 'large', question_spacing: 'comfortable', background_type: 'image', background_image_url: '/images/backgrounds/desktop/desktop-03.jpg',
      welcome_enabled: true, welcome_layout: 'center', welcome_spacing: 'standard', welcome_logo_preset: 'telescope', welcome_logo_color: '#A855F7', welcome_text_color: '#E9D5FF', welcome_button_label: 'Start', welcome_button_color: '#7C3AED', welcome_button_shape: 'round', welcome_button_size: 'medium', welcome_container_enabled: true, welcome_container_bg: '#2d1554', welcome_container_border_color: '#7C3AED', welcome_container_border_width: 1, welcome_container_animation: 'fade', welcome_logo_height: 56,
      thankyou_show_button: true, thankyou_spacing: 'standard', thankyou_logo_preset: 'telescope', thankyou_logo_color: '#A855F7', thankyou_title_color: '#E9D5FF', thankyou_button_label: 'Back to home', thankyou_button_color: '#7C3AED', thankyou_redirect_url: '/', thankyou_container_enabled: true, thankyou_container_bg: '#2d1554', thankyou_container_border_color: '#7C3AED', thankyou_container_border_width: 1, thankyou_container_animation: 'fade', thankyou_logo_height: 56 } },
]
